import {
  IconCar,
  IconBus,
  IconSteeringWheel,
  IconGauge,
  IconLuggage,
  IconRoad,
  IconMapPin,
  IconMap,
  IconCompass,
  IconNavigation,
  IconPlane,
  IconTrain,
  IconUser,
  IconUsers,
  IconGasStation,
  IconShieldCheck,
  IconCheck,
  IconAward,
  IconCertificate,
  IconLock,
  IconThumbUp,
  IconHeart,
  IconStar,
  IconPhoneCall,
  IconPhoneCalling,
  IconBrandWhatsapp,
  IconMail,
  IconMessage,
  IconMessage2,
  IconHeadset,
  IconFileText,
  IconFileCheck,
  IconFileDescription,
  IconQuote,
  IconCalendar,
  IconClock,
  IconInfoCircle,
  IconHelpCircle,
  IconBuildingArch,
  IconBuilding,
  IconHome,
  IconSettings,
  IconArrowRight,
  IconSparkles,
  IconPlus,
  IconBriefcase,
  IconCalendarEvent,
} from "@tabler/icons-astro";

export const iconResolver: Record<string, any> = {
  // Transport & Fleet
  IconCar,
  IconBus,
  IconSteeringWheel,
  IconGauge,
  IconLuggage,
  IconRoad,
  IconMapPin,
  IconMap,
  IconCompass,
  IconNavigation,
  IconPlane,
  IconTrain,
  IconUser,
  IconUsers,
  IconGasStation,

  // Trust, Safety & Quality
  IconShieldCheck,
  IconCheck,
  IconAward,
  IconCertificate,
  IconLock,
  IconThumbUp,
  IconHeart,
  IconStar,

  // Communication & Booking
  IconPhoneCall,
  IconPhoneCalling,
  IconBrandWhatsapp,
  IconMail,
  IconMessage,
  IconMessage2,
  IconHeadset,
  IconFileText,
  IconFileCheck,
  IconFileDescription,
  IconQuote,
  IconCalendar,
  IconClock,
  IconInfoCircle,
  IconHelpCircle,

  // Locations, Navigation & Miscellaneous
  IconBuildingArch,
  IconBuilding,
  IconHome,
  IconSettings,
  IconArrowRight,
  IconSparkles,
  IconPlus,
  IconBriefcase,
  IconCalendarEvent,
};
